### ISSUE TITLE
[add] 바카라 게임 구현

### ISSUE THREAD

**Issue by yeriinnn** [softeerbootcamp-3nd/be-game-insiderhj-yeriinnn#2]
## ISSUE
- 바카라 게임 구현

## To-do
- [x] 메인 게임 로직 추가
- [x] 게임유틸 클래스 추가
- [x] 메인 클래스와 게임 클래스 분리
- [x] input,output수정
